# Generated by Django 5.2.8 on 2025-11-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False, help_text='True if this is a simple repost without additional content'),
        ),
        migrations.AddField(
            model_name='post',
            name='quoted_post',
            field=models.ForeignKey(blank=True, help_text='If this is a quote post, reference to the original post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='quotes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reposts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
